ignore_merge_commits = true
branch_whitelist = []
pre_bump_hooks = []
post_bump_hooks = [
"pre-commit run"
]


[commit_types]
 # Default types: feat, fix, build, ci, revert, docs, test, style, chore, perf
# Custom types:
#release = { changelog_title = "Releases" }

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "badele"
repository = "nix-apps"
authors = [
    { username = "badele", signature = "Bruno Adelé" }
]

[bump_profiles]
